[package]
name = "toml_schema"
version = "0.1.0"
edition = "2021"
exculde = ["/test_files"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
regex = "1.10.2"
toml = "0.8.8"
