
[package]
name = {type = "string", regex = "^[a-zA-Z_-]+$"}
version = {type = "string", regex = "^[0-9]+\\.[0-9]+\\.[0-9]+$"}
edition = {type = "string"}
exculde = {type ="array", child = {type = "string"}}

[[dependencies.extras]]
key = "^[a-zA-Z_-]+$"
schema = {type = "string", regex = "^[0-9]+\\.[0-9]+\\.[0-9]+$"}